### ISSUE TITLE
Implement intersection

### ISSUE THREAD

**Issue by ZimbiX** [khiav223577/multi_range#18]
Hey, thanks for this super handy gem! We got halfway through implementing this ourselves today for time ranges, but switched over to this when we found it; and it passed all our specs once we filtered out empty ranges.

For our next piece of work, we need to get the intersection of several multi-ranges. I'd imagine this can be done by implementing intersection between two multi-ranges, e.g.:

```ruby
a = MultiRange.new([1...3, 5...10])
b = MultiRange.new([2...6, 8...9])
a.intersection(b).ranges == [2...3, 5...6, 8...9]
```

so then we could run something like:

```ruby
multi_ranges.reduce(&:intersection)
```

We'd be looking at implementing this tomorrow, and will submit a PR.

**Comment by khiav223577** [comment]
I'm glad it helps. 

If there are any questions, feel free to ask.
Looking forward to see the PR :)
