### ISSUE TITLE
Remove empty sub ranges

### ISSUE THREAD

**Issue by GerritSe** [khiav223577/multi_range#23]
Hey there! I'm playing around with your gem and it's really convenient and fits my use case well. Thanks!
However, I found that it keeps empty ranges when subtracting.

```ruby
range = MultiRange.new([540...780, 840...1080])
range -= 840...870
# => #<MultiRange:0x00007feb72c5c898 @is_float=false, @ranges=[540...780, 840...840, 870...1080]>
```

I added this spec and it failed

```ruby
assert_before_and_after(
  proc{ @multi_range.ranges },
  proc{ @multi_range -= 200..300 },
  :before => [0..100, 200..300, 500..600],
  :after => [0..100, 500..600]
)
```

While not a real issue as the ranges are empty, it's still slightly annoying and I'd like to fix it.

**Comment by khiav223577** [comment]
Hi @GerritSe,

Thanks for the report. It also looks clearer to me if we do not keep empty ranges.
Looking forward to see a PR!

**Comment by khiav223577** [comment]
I just added some comments https://github.com/khiav223577/multi_range/commit/5f185198f0ec42ccb51a2aceba7ffd585a444a4c :) 
You may want to fetch the newest master

**Comment by thomasvdpol** [comment]
When my colleagues and I were looking at this we decided against changing the behaviour as we weren't clear if it was an explicit or implicit part of the interface. I do think removing the empty ranges is good (we do so in our own code) but depending on how this gem is used elsewhere it might be good to have an option to maintain their output?

**Comment by GerritSe** [comment]
@thomasvdpol Do you have specific use cases in mind where one would miss the empty ranges?

**Comment by thomasvdpol** [comment]
> @thomasvdpol Do you have specific use cases in mind where one would miss the empty ranges?

Nope not remotely, I am just not sure how the gem is used!

**Comment by GerritSe** [comment]
@khiav223577 Do you as the owner have final thoughts on this topic? I don't have a strong opinion on the concerns @thomasvdpol raised, but making the behavior customizable would imply further design decisions (global config? constructor config? accessor config? multiple?) that need to be discussed first.

**Comment by khiav223577** [comment]
I consider it as a bug in my opinion. I have no idea in which situation someone would expect to have empty ranges being left over? While it also makes sense that we should not change the original behaviour that may being used by someone or somewhere. 

Maybe we can have a minor release (v2.1.0) for this, indicating that there is some semantic changes in this release. If someone misses empty ranges, they can leave comments here or open a new issue. We can then listen to their needs and decide whether or not to add a config for this. How do you think?

**Comment by GerritSe** [comment]
@khiav223577 Sounds good to me 👍

**Comment by khiav223577** [comment]
Just release 2.1.0
