### ISSUE TITLE
Some differences are dropped

### ISSUE THREAD

**Issue by skatenerd** [khiav223577/multi_range#29]
If we call: `(MultiRange.new([1..10]) - MultiRange.new([2..9]))`

We should get an outcome that includes both `1` and `10`.  In other words, the following should evaluate to `true`, but it does not:

` (MultiRange.new([1..10]) - MultiRange.new([2..9])).overlaps?(10..10)`

It's interesting, because if we increase the "right hand side delta" to be larger than just one number, then the code behaves as expected:

`(MultiRange.new([1..10]) - MultiRange.new([2...9])).overlaps?(10..10)` => `true`

**Comment by skatenerd** [comment]
I wonder if the fix is as simple as this?
<img width="815" alt="image" src="https://github.com/khiav223577/multi_range/assets/880217/e2518a83-e7db-443c-bdbb-f9b42e9532bf">

**Comment by khiav223577** [comment]
Just release v2.2.0, See the [changelog](https://github.com/khiav223577/multi_range/blob/master/CHANGELOG.md) for more details.
