### ISSUE TITLE
Intersection is empty when it should not be

### ISSUE THREAD

**Issue by skatenerd** [khiav223577/multi_range#30]
If we call:
`MultiRange.new([10..10]) & MultiRange.new([10..20])`

We should get a nonempty range.  But I am seeing an empty range instead.  Interestingly, the behavior is not commutative.  If I flip the two arguments, I get a nonempty range.

**Comment by skatenerd** [comment]
I wonder if the fix is as simple as this?
<img width="390" alt="image" src="https://github.com/khiav223577/multi_range/assets/880217/05e70362-5a28-4955-a178-7208bc710c82">

**Comment by khiav223577** [comment]
Thanks for the report. I submitted an issue to fast_interval_tree: https://github.com/greensync/interval-tree/issues/17
And add a workaround for the issue in https://github.com/khiav223577/multi_range/pull/33

**Comment by khiav223577** [comment]
Just release v2.2.0, See the [changelog](https://github.com/khiav223577/multi_range/blob/master/CHANGELOG.md) for more details.
