### ISSUE TITLE
Intersection should never be bigger than the inputs

### ISSUE THREAD

**Issue by skatenerd** [khiav223577/multi_range#31]
`MultiRange.new([10...10]) & MultiRange.new([10..10])`

Because the first argument is empty, this should give an empty output.  But the output actually contains `10..10`.

**Comment by khiav223577** [comment]
Hi @skatenerd, I test the case with latest version (v2.1.1), the behavior looks the same as what you expected.
Could you try out the latest version?

```rb
MultiRange::VERSION
# => "2.1.1"

MultiRange.new([10...10]) & MultiRange.new([10..10])
# => #<MultiRange:0x00007fffbea46b48 @ranges=[], @is_float=false>
```

**Comment by skatenerd** [comment]
Awesome, thank you!!

**Comment by skatenerd** [comment]
@khiav223577 I am still seeing this issue locally 🤔

**Comment by skatenerd** [comment]
@khiav223577 I am seeing the good behavior on that version of the code.  I just want to note, I think the [range-intersection code](https://github.com/khiav223577/multi_range/blob/dfacb939bb0faa8c42c51daaf10a520c5eee74e4/lib/multi_range.rb#L228) does not behave how I would expect??

<img width="1060" alt="image" src="https://github.com/khiav223577/multi_range/assets/880217/bd156305-61f1-4c71-aaeb-3d79a8db0598">

**Comment by skatenerd** [comment]
Hmm, strangely, this issue does present on version `2.2.0`

<img width="948" alt="image" src="https://github.com/khiav223577/multi_range/assets/880217/f2d47ac8-0f25-451d-93c1-cc0cd1c8a244">

**Comment by khiav223577** [comment]
Look like `MultiRange.new([10..10]) & MultiRange.new([10...10])` is wrong in both v2.1.1 and v2.2.0
and `MultiRange.new([10...10]) & MultiRange.new([10..10])` is correct in v2.1.1 but is wrong in v2.2.0 (caused by https://github.com/khiav223577/multi_range/pull/33)

**Comment by khiav223577** [comment]
Just release v2.2.1. :)
